### PR TITLE
Fixed some bugs , UI also improved

### PR DESCRIPTION
**Pull request by Rupam-Mondal**
I fixed some bugs. User can not add todo without given full details also i added time feature

### CODE REVIEW

**Comment by Anshgrover23** [comment]
@Rupam-Mondal thanks for your contribution bro.

**Comment by Anshgrover23** [comment]
@Rupam-Mondal May i  know where i can contact with you specifically. i want to know something from you

**Comment by Rupam-Mondal** [comment]
https://www.linkedin.com/in/rupam-mondal-37b653252?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app
you can send me message here

**Comment by Anshgrover23** [comment]
@Rupam-Mondal please give a star to my repository and try to solve issue #8 it is the continuation of your pr

**Pull request merged**
