### PR TITLE
Time section added and bug fixed

### PR DESCRIPTION
**Pull request by Rupam-Mondal**
Previously user can add todo list without name and data that is a bad user experience so i added that user have to give valid todo name data and time. This will enhance the user experience also i added the time feature also it is editable

### CODE REVIEW

**Comment by Rupam-Mondal** [comment]
I raised a PR with a update of this tier list. Waiting for your response thank you

**Comment by Anshgrover23** [comment]
@Rupam-Mondal thanks for your contribution. can u please update this styling 
image

**Comment by Rupam-Mondal** [comment]
> @Rupam-Mondal thanks for your contribution. can u please update this styling image

Thanks for commenting. Can you kindly merge this pr because that will increase my pull request acceptance number and also i am improving the styling. Thanks

**Comment by Anshgrover23** [comment]
@Rupam-Mondal yes i will surely merge it whenever you are ready to make the styling better in further commits  ping me here.

**Comment by Anshgrover23** [comment]
@Rupam-Mondal hey, is there anything wrong why have you closed your pr?

**Comment by Rupam-Mondal** [comment]
actually i told that there is a issue going on my github i am not able to
create more than one pr i do not why. So the styling pr was not been
created that's why i thought to close because you told only when i will
update ui then you merge i am trying again to raise pr

**Comment by Rupam-Mondal** [comment]
also can u pls mention what ui change you need so that i can help further

**Comment by Anshgrover23** [comment]
@Rupam-Mondal ok. So you see in image there is a delete, button and everything is becoming bubbly now on. Make them look alike same.as before and make a new box for showing time. If you think it's not needed then don't worry. Don't need to make a separate container for that

**Comment by Anshgrover23** [comment]
@Rupam-Mondal I am reopening this pr now

**Comment by Anshgrover23** [comment]
@Rupam-Mondal I hope you understand.if need further help pls ping me.

**Comment by Rupam-Mondal** [comment]
I am raising PR check once I have solved the UI issue

**Pull request closed without merging**
